In [7]:
#Πρώτα ένα check του file:

import pandas as pd
from IPython.display import display

data = pd.read_csv(r"C:\Users\Owner\Desktop\Essex\03. Main\Data\Python\Group Project\Data Clean\youtube_comments_annotated_cleaned.csv")

print(data.info())
print('-'*90)
print(data.columns)
print('-'*90)
print(data.head())

#Έχουμε 0 nulls και οι στύλες που θέλουμε είναι εκεί.

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   comment_id         1000 non-null   str
 1   author_name        1000 non-null   str
 2   topic              1000 non-null   str
 3   video_title        1000 non-null   str
 4   video_channel      1000 non-null   str
 5   text               1000 non-null   str
 6   annotator_1_label  1000 non-null   str
 7   annotator_2_label  1000 non-null   str
 8   annotator_3_label  1000 non-null   str
 9   sentiment_label    1000 non-null   str
 10  clean_text         937 non-null    str
dtypes: str(11)
memory usage: 86.1 KB
None
------------------------------------------------------------------------------------------
Index(['comment_id', 'author_name', 'topic', 'video_title', 'video_channel',
       'text', 'annotator_1_label', 'annotator_2_label', 'annotator_3_label',
       'sentiment_label', 'clean_text'],
      dtype='str')
------------------------------------------------------------------------------------------
                   comment_id        author_name     topic  \
0  UgxrCmSeVh41IcaQYHV4AaABAg      @Spanishkid97  Football
1  UgzYV_zK1zww1WW0Z5p4AaABAg   @Sathyabhama-z3d  Football
2  UgyR2PQD_ZodUbZ-4l54AaABAg       @NinetyVirus  Football
3  UgzLvjrmCElWu91BsTN4AaABAg  @fardianazmar7156  Football
4  UgwEwc_rrl-OKmA0J_54AaABAg  @greek_gaming1328  Football

                                         video_title          video_channel  \
0  Carolina Panthers vs. Arizona Cardinals | 2026...                    NFL
1  SPAIN 1-0 ARGENTINA | FIFA WORLD CUP 2026 FINA...              BOBOLA TV
2                       Scariest Moments In Football                 Ninety
3  Chelsea 0-1 Juventus | HIGHLIGHTS | Pre-Season...  Chelsea Football Club
4  Unbelievable Moments In Football | Al Nassr VS...         CrossBar Editz

                                               text annotator_1_label  \
0                            Haynes king is HIM😤!!!          positive
1                                           Vbvgdff           neutral
2  Greatest game on earth, but also the scariest? 🥶          positive
3                                               🤣🤣🤣           neutral
4                                 God Ronaldo ⚽⚽⚽⚽⚽          positive

  annotator_2_label annotator_3_label sentiment_label  \
0          positive          positive        positive
1           neutral           neutral         neutral
2          positive          positive        positive
3          positive          positive        positive
4          positive          positive        positive

                          clean_text
0                        haynes king
1                            vbvgdff
2  greatest game earth also scariest
3                                NaN
4                        god ronaldo

In [3]:
#Μετά ένα γρήγηρο check nulls & Duplicates on commend_id only γιατί πρέπει να είναι unique.

print(data.isnull().sum())
print('-'*90)
print("Duplicate comment IDs:", data['comment_id'].duplicated().sum())

#Όλα οκ.

comment_id            0
author_name           0
topic                 0
video_title           0
video_channel         0
text                  0
annotator_1_label     0
annotator_2_label     0
annotator_3_label     0
sentiment_label       0
clean_text           63
dtype: int64
------------------------------------------------------------------------------------------
Duplicate comment IDs: 0

In [8]:
#Closer look at the file:

print("Topic counts:")
print(data['topic'].value_counts())
print("\nSentiment counts:")
print(data['sentiment_label'].value_counts())
data[['comment_id', 'topic', 'text', 'sentiment_label']].head(10)

#sentiment_label έχει όντως 1000 Values και κανένα Nan ενώ είναι μόνο 3 entries: Positive/Negative/Neutral

Topic counts:
topic
Football                   250
Climate Change             250
Video Games                250
Artificial Intelligence    250
Name: count, dtype: int64

Sentiment counts:
sentiment_label
negative    352
neutral     343
positive    305
Name: count, dtype: int64

,comment_id,topic,text,sentiment_label
0,UgxrCmSeVh41IcaQYHV4AaABAg,Football,Haynes king is HIM😤!!!,positive
1,UgzYV_zK1zww1WW0Z5p4AaABAg,Football,Vbvgdff,neutral
2,UgyR2PQD_ZodUbZ-4l54AaABAg,Football,"Greatest game on earth, but also the scariest? 🥶",positive
3,UgzLvjrmCElWu91BsTN4AaABAg,Football,🤣🤣🤣,positive
4,UgwEwc_rrl-OKmA0J_54AaABAg,Football,God Ronaldo ⚽⚽⚽⚽⚽,positive
5,Ugyhj05JeMNyWipqxVp4AaABAg,Football,8:34 what a clown piece from Ramos,negative
6,UgzkYdjfSBCmg3p0JfB4AaABAg,Football,"Trust me, even I can score that 1CM goal 😏",negative
7,UgxLBvsU6eZhWhcYA1x4AaABAg,Football,🚨YES GUYS! Who's team is better? Team Billy & ...,neutral
8,UgyhV_Isqm3AhYD0IOx4AaABAg,Football,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...,negative
9,Ugwgs8WvNb146n7wMZV4AaABAg,Football,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...,positive

In [5]:
#New column to the file named as "clean_text". Αυτό για να μπορέσουμε στο τέλος να συγκρίνουμε.

data['clean_text'] = data['text']  #<---Νέο column ίδιο με το text.
data['clean_text'] = data['clean_text'].str.lower()  #<----Lowering strings texts
data[['text', 'clean_text']].head(10)  #<<---print 10 lines for check

#OK

,text,clean_text
0,Haynes king is HIM😤!!!,haynes king is him😤!!!
1,Vbvgdff,vbvgdff
2,"Greatest game on earth, but also the scariest? 🥶","greatest game on earth, but also the scariest? 🥶"
3,🤣🤣🤣,🤣🤣🤣
4,God Ronaldo ⚽⚽⚽⚽⚽,god ronaldo ⚽⚽⚽⚽⚽
5,8:34 what a clown piece from Ramos,8:34 what a clown piece from ramos
6,"Trust me, even I can score that 1CM goal 😏","trust me, even i can score that 1cm goal 😏"
7,🚨YES GUYS! Who's team is better? Team Billy & ...,🚨yes guys! who's team is better? team billy & ...
8,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...
9,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...

In [6]:
#URL removal with regex

data['clean_text'] = data['clean_text'].str.replace(r'http\S+|www\.\S+','',regex=True)
display(data[['text', 'clean_text']].head(10))

,text,clean_text
0,Haynes king is HIM😤!!!,haynes king is him😤!!!
1,Vbvgdff,vbvgdff
2,"Greatest game on earth, but also the scariest? 🥶","greatest game on earth, but also the scariest? 🥶"
3,🤣🤣🤣,🤣🤣🤣
4,God Ronaldo ⚽⚽⚽⚽⚽,god ronaldo ⚽⚽⚽⚽⚽
5,8:34 what a clown piece from Ramos,8:34 what a clown piece from ramos
6,"Trust me, even I can score that 1CM goal 😏","trust me, even i can score that 1cm goal 😏"
7,🚨YES GUYS! Who's team is better? Team Billy & ...,🚨yes guys! who's team is better? team billy & ...
8,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...
9,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...

In [9]:
#Από τις 10 πρώτες rows δεν έχει urls, ας τα βρούμε.

url_rows = data[data['text'].str.contains(r'http\S+|www\.\S+',regex=True,na=False)]
display(url_rows[['text', 'clean_text']].head(10))

#URLs removed confirmed.

,text,clean_text
20,Missed the OG Pop drop? 🔥Extended for a limit...,missed og pop drop extended limited time
260,Head over to our shop to get exclusive kurzges...,head shop get exclusive kurzgesagt merch scien...
268,"😃 If you want to improve your English Fluency,...",want improve english fluency try fluency ielts...
270,😊 Click here for a vocabulary list and a trans...,click vocabulary list transcript
281,Full video : Don't blindly rush into 'good' de...,full video blindly rush good deeds acharya pra...
285,Click here to subscribe to our channel 👉🏽 http...,click subscribe channel
512,New Game - https://youtu.be/OS5prnmxbak,new game
518,M15 Game Stick full video :- https://youtu.be/...,m15 game stick full video gs5 pro unboxing rev...
528,💜 SUBSCRIBE 👉 https://s2m.lnk.to/Sing2PianoYT1...,subscribe sing lana del rey use tracks newsletter
531,Ready for some Mario Party fun? Watch my new v...,ready mario party fun watch new video

In [10]:
#Removing "mentions".Find & Remove to make sure.

data['clean_text'] = data['clean_text'].str.replace(r'@\w+','',regex=True)

mention_rows = data[data['text'].str.contains(r'@\w+', regex=True, na=False)]
display(mention_rows[['text', 'clean_text']].head(10))
print('-'*80)
print("Rows with mentions:", len(mention_rows))
print("Mentions remaining:",data['clean_text'].str.contains(r'@\w+', regex=True, na=False).sum())

,text,clean_text
246,"Not even a fan of both of these teams, but why...",even fan teams tf carson beck thumbnail know s...
536,Credits to @LightningMcQueen2017Games for usin...,credits using mod base using personalized rims...
830,I offer this with sincerity. I think you truly...,offer sincerity think truly genuine approach t...
925,[❌ FATAL ERROR: Transaction failed. Reason: Ta...,fatal error transaction failed reason target a...

--------------------------------------------------------------------------------
Rows with mentions: 4
Mentions remaining: 0

In [11]:
#Remove hashtags , same way.

data['clean_text'] = data['clean_text'].str.replace(r'#\w+','',regex=True)

hashtag_rows = data[data['text'].str.contains(r'#\w+', regex=True, na=False)]
display(hashtag_rows[['text', 'clean_text']].head(10))
print('-'*80)
print("Rows with hashtags:", len(hashtag_rows))
print("Hashtags remaining:",data['clean_text'].str.contains(r'#\w+', regex=True, na=False).sum())

,text,clean_text
632,SNL Performance #1. Daniel Radcliffe: Ladies a...,snl performance daniel radcliffe ladies gentle...
729,"IfuBav3u 1i in wybn[2, ^3&,p2 on ^2^(p2md 3&# ...",ifubav3u 1i wybn 2 3 p2 2 p2md 3 o2o n g lkd 2...

--------------------------------------------------------------------------------
Rows with hashtags: 2
Hashtags remaining: 0

In [12]:
#Remove special characters. (! ? . , : ; ( ) [ ] " ' / \ ❤️ 😂 🔥)
#Από τη στιγμή που τα commends είναι annotated εγώ δεν βλέπω λόγο να κρατήσουμε emojis. Οπότε και φύγανε.

data['clean_text'] = data['clean_text'].str.replace(r'[^\w\s]|_',' ',regex=True)
special_rows = data[data['text'].str.contains(r'[^\w\s]|_', regex=True, na=False)]
display(special_rows[['text', 'clean_text']].head(10))
print('-'*80)
print("Rows with special characters:", len(special_rows))
print("Special characters remaining:",data['clean_text'].str.contains(r'[^\w\s]|_', regex=True, na=False).sum())

,text,clean_text
0,Haynes king is HIM😤!!!,haynes king
2,"Greatest game on earth, but also the scariest? 🥶",greatest game earth also scariest
3,🤣🤣🤣,NaN
4,God Ronaldo ⚽⚽⚽⚽⚽,god ronaldo
5,8:34 what a clown piece from Ramos,8 34 clown piece ramos
6,"Trust me, even I can score that 1CM goal 😏",trust even score 1cm goal
7,🚨YES GUYS! Who's team is better? Team Billy & ...,yes guys team better team billy dustie team ro...
8,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...,저 ㅈㄹ을 해도 막판에 골을 못 넣는데
9,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...,ন ম র
10,🇵🇹🇵🇹🇵🇹🇵🇹,NaN

--------------------------------------------------------------------------------
Rows with special characters: 750
Special characters remaining: 0

In [13]:
#Import NLTK for "stopwords"

import nltk
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

In [14]:
#Cleaning with NLTK stopwords

data['clean_text'] = data['clean_text'].apply(lambda text: ' '.join(word for word in text.split()
                                                                    if word not in stop_words))
display(data[['text', 'clean_text']].head(10))

AttributeError: 'float' object has no attribute 'split'

In [29]:
#Removing whitespace (multiple spaces in the text)

data['clean_text'] = data['clean_text'].str.replace(r'\s+',' ',regex=True).str.strip()
display(data[['text', 'clean_text']].head(10))
print('-'*80)
print("Rows with multiple spaces remaining:",data['clean_text'].str.contains(r'\s{2,}', regex=True, na=False).sum())

,text,clean_text
0,Haynes king is HIM😤!!!,haynes king
1,Vbvgdff,vbvgdff
2,"Greatest game on earth, but also the scariest? 🥶",greatest game earth also scariest
3,🤣🤣🤣,
4,God Ronaldo ⚽⚽⚽⚽⚽,god ronaldo
5,8:34 what a clown piece from Ramos,8 34 clown piece ramos
6,"Trust me, even I can score that 1CM goal 😏",trust even score 1cm goal
7,🚨YES GUYS! Who's team is better? Team Billy & ...,yes guys team better team billy dustie team ro...
8,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...,저 ㅈㄹ을 해도 막판에 골을 못 넣는데
9,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...,ন ম র

--------------------------------------------------------------------------------
Rows with multiple spaces remaining: 0

In [31]:
#Inspecting for empty entries after the whole pipeline of cleaning.

empty_rows = data[data['clean_text'].str.strip() == '']
print("Empty clean_text rows:", len(empty_rows))
print('-'*80)
display(empty_rows[['text', 'clean_text', 'sentiment_label']].head(10))
print('-'*80)
display(empty_rows[['text', 'topic', 'sentiment_label']].head(20))

Empty clean_text rows: 63
--------------------------------------------------------------------------------

,text,clean_text,sentiment_label
3,🤣🤣🤣,,positive
10,🇵🇹🇵🇹🇵🇹🇵🇹,,positive
11,❤,,positive
23,👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍...,,positive
29,❤,,positive
52,It❤,,positive
71,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷⚽❤❤,,positive
85,😮😮😮😮,,positive
102,😘😘😘🤫🤫🫡🫡😏😎😇🥹🥹🥹,,positive
116,🎉🎉🎉🎉🎉,,positive

--------------------------------------------------------------------------------

,text,topic,sentiment_label
3,🤣🤣🤣,Football,positive
10,🇵🇹🇵🇹🇵🇹🇵🇹,Football,positive
11,❤,Football,positive
23,👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍...,Football,positive
29,❤,Football,positive
...,...,...,...
733,❤😂🎉😢😮😅😊😊,Video Games,neutral
809,🙄,Artificial Intelligence,negative
903,What?,Artificial Intelligence,neutral
904,🇺🇸👁️🇺🇸👁️🇺🇸🌍🧠💡🧠💡🧠,Artificial Intelligence,neutral
968,D,Artificial Intelligence,neutral

In [33]:
#Quick check of the dataset after cleaning text column to clean_text column.

print("Final shape:", data.shape)
print('-' * 80)
print("Missing values in key columns:")
print(data[['comment_id', 'text', 'clean_text', 'topic', 'sentiment_label']].isnull().sum())
print('-' * 80)
print("Duplicate comment IDs:", data['comment_id'].duplicated().sum())
print('-' * 80)
print("Empty clean_text rows:", (data['clean_text'].str.strip() == '').sum())
print('-' * 80)
print("Topic counts:")
print(data['topic'].value_counts())
print('-' * 80)
print("Sentiment counts:")
print(data['sentiment_label'].value_counts())

#File remained same and balanced.

Final shape: (1000, 11)
--------------------------------------------------------------------------------
Missing values in key columns:
comment_id         0
text               0
clean_text         0
topic              0
sentiment_label    0
dtype: int64
--------------------------------------------------------------------------------
Duplicate comment IDs: 0
--------------------------------------------------------------------------------
Empty clean_text rows: 63
--------------------------------------------------------------------------------
Topic counts:
topic
Football                   250
Climate Change             250
Video Games                250
Artificial Intelligence    250
Name: count, dtype: int64
--------------------------------------------------------------------------------
Sentiment counts:
sentiment_label
negative    352
neutral     343
positive    305
Name: count, dtype: int64

In [34]:
#Saving changes to csv file.

data.to_csv(r"C:\Users\Owner\Desktop\Essex\03. Main\Data\Python\Group Project\Data Clean\youtube_comments_annotated_cleaned.csv",index=False)
print("File saved successfully.")

File saved successfully.

In [37]:
#Inspecting the new file.

check_data = pd.read_csv(r"C:\Users\Owner\Desktop\Essex\03. Main\Data\Python\Group Project\Data Clean\youtube_comments_annotated_cleaned.csv")

print("Shape:", check_data.shape)
print("Columns:")
print(check_data.columns)
print('-' * 80)
print("Empty clean_text rows:",(check_data['clean_text'].str.strip() == '').sum())
print('-' * 80)
display(check_data[['text', 'clean_text']].head(10))


#Επειδή κάποια clean_text entries έμειναν άδεια θα τα βλέπει πλέον ως null

print('-' * 80)
print("NaN clean_text rows:", check_data['clean_text'].isna().sum())

Shape: (1000, 11)
Columns:
Index(['comment_id', 'author_name', 'topic', 'video_title', 'video_channel',
       'text', 'annotator_1_label', 'annotator_2_label', 'annotator_3_label',
       'sentiment_label', 'clean_text'],
      dtype='str')
--------------------------------------------------------------------------------
Empty clean_text rows: 0
--------------------------------------------------------------------------------

,text,clean_text
0,Haynes king is HIM😤!!!,haynes king
1,Vbvgdff,vbvgdff
2,"Greatest game on earth, but also the scariest? 🥶",greatest game earth also scariest
3,🤣🤣🤣,NaN
4,God Ronaldo ⚽⚽⚽⚽⚽,god ronaldo
5,8:34 what a clown piece from Ramos,8 34 clown piece ramos
6,"Trust me, even I can score that 1CM goal 😏",trust even score 1cm goal
7,🚨YES GUYS! Who's team is better? Team Billy & ...,yes guys team better team billy dustie team ro...
8,저 ㅈㄹ을 해도 막판에 골을 못 넣는데...,저 ㅈㄹ을 해도 막판에 골을 못 넣는데
9,🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️...,ন ম র

--------------------------------------------------------------------------------
NaN clean_text rows: 63